# Generated by Django 5.1.3 on 2024-11-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_order_date_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
